"""initial

Revision ID: db74a32f37a1
Revises: 
Create Date: 2026-02-07 21:13:51.394782+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db74a32f37a1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('abbreviation', sa.String(length=20), nullable=True),
    sa.Column('foia_email', sa.String(length=255), nullable=True),
    sa.Column('foia_phone', sa.String(length=50), nullable=True),
    sa.Column('foia_address', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('jurisdiction', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('avg_response_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('news_articles',
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('headline', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('incident_type', sa.Enum('ois', 'use_of_force', 'pursuit', 'taser', 'k9', 'arrest', 'dui', 'other', name='incident_type_enum'), nullable=True),
    sa.Column('severity_score', sa.Integer(), nullable=True),
    sa.Column('detected_agency', sa.String(length=255), nullable=True),
    sa.Column('detected_officers', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('detected_location', sa.String(length=500), nullable=True),
    sa.Column('is_reviewed', sa.Boolean(), nullable=False),
    sa.Column('is_dismissed', sa.Boolean(), nullable=False),
    sa.Column('dismissed_reason', sa.String(length=500), nullable=True),
    sa.Column('auto_foia_eligible', sa.Boolean(), nullable=False),
    sa.Column('auto_foia_filed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_news_articles_published_at'), 'news_articles', ['published_at'], unique=False)
    op.create_index(op.f('ix_news_articles_severity_score'), 'news_articles', ['severity_score'], unique=False)
    op.create_table('notifications',
    sa.Column('type', sa.Enum('foia_submitted', 'foia_acknowledged', 'foia_fulfilled', 'foia_denied', 'foia_overdue', 'scan_complete', 'video_uploaded', 'video_published', 'revenue_milestone', 'system_error', name='notification_type_enum'), nullable=False),
    sa.Column('channel', sa.Enum('email', 'sms', 'in_app', name='notification_channel_enum'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_logs',
    sa.Column('scan_type', sa.Enum('rss', 'scrape', 'imap', name='scan_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('running', 'completed', 'failed', name='scan_status_enum'), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('articles_found', sa.Integer(), nullable=False),
    sa.Column('articles_new', sa.Integer(), nullable=False),
    sa.Column('articles_duplicate', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('foia_requests',
    sa.Column('case_number', sa.String(length=20), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('news_article_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'ready', 'submitted', 'acknowledged', 'processing', 'fulfilled', 'partial', 'denied', 'appealed', 'closed', name='foia_status_enum'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='foia_priority_enum'), nullable=False),
    sa.Column('request_text', sa.Text(), nullable=False),
    sa.Column('pdf_storage_key', sa.String(length=500), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agency_reference_number', sa.String(length=100), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('response_emails', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_auto_submitted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['news_article_id'], ['news_articles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number')
    )
    op.create_index(op.f('ix_foia_requests_due_date'), 'foia_requests', ['due_date'], unique=False)
    op.create_index(op.f('ix_foia_requests_status'), 'foia_requests', ['status'], unique=False)
    op.create_table('videos',
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('foia_request_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('raw_received', 'editing', 'ai_processing', 'review', 'ready', 'uploading', 'published', 'archived', name='video_status_enum'), nullable=False),
    sa.Column('raw_storage_key', sa.String(length=500), nullable=True),
    sa.Column('processed_storage_key', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_storage_key', sa.String(length=500), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('youtube_video_id', sa.String(length=50), nullable=True),
    sa.Column('youtube_url', sa.String(length=500), nullable=True),
    sa.Column('youtube_upload_status', sa.String(length=50), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('editing_notes', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['foia_request_id'], ['foia_requests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revenue_transactions',
    sa.Column('video_id', sa.UUID(), nullable=True),
    sa.Column('foia_request_id', sa.UUID(), nullable=True),
    sa.Column('transaction_type', sa.Enum('youtube_adsense', 'sponsorship', 'licensing', 'foia_cost', 'editing_cost', 'equipment', 'other_income', 'other_expense', name='transaction_type_enum'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('is_income', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['foia_request_id'], ['foia_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revenue_transactions_transaction_date'), 'revenue_transactions', ['transaction_date'], unique=False)
    op.create_table('video_analytics',
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('watch_time_minutes', sa.Float(), nullable=False),
    sa.Column('estimated_revenue', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=False),
    sa.Column('subscribers_gained', sa.Integer(), nullable=False),
    sa.Column('subscribers_lost', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('dislikes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', 'date', name='uq_video_analytics_video_date')
    )
    op.create_index(op.f('ix_video_analytics_date'), 'video_analytics', ['date'], unique=False)
    op.create_index(op.f('ix_video_analytics_video_id'), 'video_analytics', ['video_id'], unique=False)
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('key'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_settings')
    op.drop_index(op.f('ix_video_analytics_video_id'), table_name='video_analytics')
    op.drop_index(op.f('ix_video_analytics_date'), table_name='video_analytics')
    op.drop_table('video_analytics')
    op.drop_index(op.f('ix_revenue_transactions_transaction_date'), table_name='revenue_transactions')
    op.drop_table('revenue_transactions')
    op.drop_table('videos')
    op.drop_index(op.f('ix_foia_requests_status'), table_name='foia_requests')
    op.drop_index(op.f('ix_foia_requests_due_date'), table_name='foia_requests')
    op.drop_table('foia_requests')
    op.drop_table('scan_logs')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_news_articles_severity_score'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_published_at'), table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_table('agencies')
    # ### end Alembic commands ###
